CRITICAL - 2020-12-08 00:30:04 --> Undefined variable: keranjang
#0 C:\xampp\htdocs\UtsWeb\app\Views\auth\beli.php(28): CodeIgniter\Debug\Exceptions->errorHandler(8, 'Undefined varia...', 'C:\\xampp\\htdocs...', 28, Array)
#1 C:\xampp\htdocs\UtsWeb\system\View\View.php(246): include('C:\\xampp\\htdocs...')
#2 C:\xampp\htdocs\UtsWeb\system\Common.php(1119): CodeIgniter\View\View->render('auth/beli', Array, true)
#3 C:\xampp\htdocs\UtsWeb\app\Controllers\Auth.php(15): view('auth/beli')
#4 C:\xampp\htdocs\UtsWeb\system\CodeIgniter.php(918): App\Controllers\Auth->beli()
#5 C:\xampp\htdocs\UtsWeb\system\CodeIgniter.php(404): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Auth))
#6 C:\xampp\htdocs\UtsWeb\system\CodeIgniter.php(312): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#7 C:\xampp\htdocs\UtsWeb\public\index.php(45): CodeIgniter\CodeIgniter->run()
#8 C:\xampp\htdocs\UtsWeb\system\Commands\Server\rewrite.php(34): require_once('C:\\xampp\\htdocs...')
#9 {main}
CRITICAL - 2020-12-08 00:41:08 --> Invalid file: /kopi.php
#0 C:\xampp\htdocs\UtsWeb\system\View\View.php(228): CodeIgniter\Exceptions\FrameworkException::forInvalidFile('/kopi.php')
#1 C:\xampp\htdocs\UtsWeb\system\Common.php(1119): CodeIgniter\View\View->render('/kopi', Array, true)
#2 C:\xampp\htdocs\UtsWeb\app\Controllers\Auth.php(15): view('/kopi')
#3 C:\xampp\htdocs\UtsWeb\system\CodeIgniter.php(918): App\Controllers\Auth->beli()
#4 C:\xampp\htdocs\UtsWeb\system\CodeIgniter.php(404): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Auth))
#5 C:\xampp\htdocs\UtsWeb\system\CodeIgniter.php(312): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#6 C:\xampp\htdocs\UtsWeb\public\index.php(45): CodeIgniter\CodeIgniter->run()
#7 C:\xampp\htdocs\UtsWeb\system\Commands\Server\rewrite.php(34): require_once('C:\\xampp\\htdocs...')
#8 {main}
CRITICAL - 2020-12-08 00:43:42 --> Class 'App\Controllers\KopiModel' not found
#0 C:\xampp\htdocs\UtsWeb\system\CodeIgniter.php(890): App\Controllers\Auth->__construct()
#1 C:\xampp\htdocs\UtsWeb\system\CodeIgniter.php(399): CodeIgniter\CodeIgniter->createController()
#2 C:\xampp\htdocs\UtsWeb\system\CodeIgniter.php(312): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#3 C:\xampp\htdocs\UtsWeb\public\index.php(45): CodeIgniter\CodeIgniter->run()
#4 C:\xampp\htdocs\UtsWeb\system\Commands\Server\rewrite.php(34): require_once('C:\\xampp\\htdocs...')
#5 {main}
CRITICAL - 2020-12-08 00:44:12 --> Class 'App\Controllers\KopiModel' not found
#0 C:\xampp\htdocs\UtsWeb\system\CodeIgniter.php(890): App\Controllers\Auth->__construct()
#1 C:\xampp\htdocs\UtsWeb\system\CodeIgniter.php(399): CodeIgniter\CodeIgniter->createController()
#2 C:\xampp\htdocs\UtsWeb\system\CodeIgniter.php(312): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#3 C:\xampp\htdocs\UtsWeb\public\index.php(45): CodeIgniter\CodeIgniter->run()
#4 C:\xampp\htdocs\UtsWeb\system\Commands\Server\rewrite.php(34): require_once('C:\\xampp\\htdocs...')
#5 {main}
CRITICAL - 2020-12-08 00:44:12 --> Class 'App\Controllers\KopiModel' not found
#0 C:\xampp\htdocs\UtsWeb\system\CodeIgniter.php(890): App\Controllers\Auth->__construct()
#1 C:\xampp\htdocs\UtsWeb\system\CodeIgniter.php(399): CodeIgniter\CodeIgniter->createController()
#2 C:\xampp\htdocs\UtsWeb\system\CodeIgniter.php(312): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#3 C:\xampp\htdocs\UtsWeb\public\index.php(45): CodeIgniter\CodeIgniter->run()
#4 C:\xampp\htdocs\UtsWeb\system\Commands\Server\rewrite.php(34): require_once('C:\\xampp\\htdocs...')
#5 {main}
CRITICAL - 2020-12-08 00:44:13 --> Class 'App\Controllers\KopiModel' not found
#0 C:\xampp\htdocs\UtsWeb\system\CodeIgniter.php(890): App\Controllers\Auth->__construct()
#1 C:\xampp\htdocs\UtsWeb\system\CodeIgniter.php(399): CodeIgniter\CodeIgniter->createController()
#2 C:\xampp\htdocs\UtsWeb\system\CodeIgniter.php(312): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#3 C:\xampp\htdocs\UtsWeb\public\index.php(45): CodeIgniter\CodeIgniter->run()
#4 C:\xampp\htdocs\UtsWeb\system\Commands\Server\rewrite.php(34): require_once('C:\\xampp\\htdocs...')
#5 {main}
CRITICAL - 2020-12-08 00:45:52 --> Class 'App\Controllers\KopiModel' not found
#0 C:\xampp\htdocs\UtsWeb\system\CodeIgniter.php(890): App\Controllers\Auth->__construct()
#1 C:\xampp\htdocs\UtsWeb\system\CodeIgniter.php(399): CodeIgniter\CodeIgniter->createController()
#2 C:\xampp\htdocs\UtsWeb\system\CodeIgniter.php(312): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#3 C:\xampp\htdocs\UtsWeb\public\index.php(45): CodeIgniter\CodeIgniter->run()
#4 C:\xampp\htdocs\UtsWeb\system\Commands\Server\rewrite.php(34): require_once('C:\\xampp\\htdocs...')
#5 {main}
CRITICAL - 2020-12-08 00:45:54 --> Class 'App\Controllers\KopiModel' not found
#0 C:\xampp\htdocs\UtsWeb\system\CodeIgniter.php(890): App\Controllers\Auth->__construct()
#1 C:\xampp\htdocs\UtsWeb\system\CodeIgniter.php(399): CodeIgniter\CodeIgniter->createController()
#2 C:\xampp\htdocs\UtsWeb\system\CodeIgniter.php(312): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#3 C:\xampp\htdocs\UtsWeb\public\index.php(45): CodeIgniter\CodeIgniter->run()
#4 C:\xampp\htdocs\UtsWeb\system\Commands\Server\rewrite.php(34): require_once('C:\\xampp\\htdocs...')
#5 {main}
CRITICAL - 2020-12-08 00:45:58 --> Class 'App\Controllers\KopiModel' not found
#0 C:\xampp\htdocs\UtsWeb\system\CodeIgniter.php(890): App\Controllers\Auth->__construct()
#1 C:\xampp\htdocs\UtsWeb\system\CodeIgniter.php(399): CodeIgniter\CodeIgniter->createController()
#2 C:\xampp\htdocs\UtsWeb\system\CodeIgniter.php(312): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#3 C:\xampp\htdocs\UtsWeb\public\index.php(45): CodeIgniter\CodeIgniter->run()
#4 C:\xampp\htdocs\UtsWeb\system\Commands\Server\rewrite.php(34): require_once('C:\\xampp\\htdocs...')
#5 {main}
CRITICAL - 2020-12-08 00:46:38 --> Invalid file: /kopi.php
#0 C:\xampp\htdocs\UtsWeb\system\View\View.php(228): CodeIgniter\Exceptions\FrameworkException::forInvalidFile('/kopi.php')
#1 C:\xampp\htdocs\UtsWeb\system\Common.php(1119): CodeIgniter\View\View->render('/kopi', Array, true)
#2 C:\xampp\htdocs\UtsWeb\app\Controllers\Auth.php(15): view('/kopi')
#3 C:\xampp\htdocs\UtsWeb\system\CodeIgniter.php(918): App\Controllers\Auth->beli()
#4 C:\xampp\htdocs\UtsWeb\system\CodeIgniter.php(404): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Auth))
#5 C:\xampp\htdocs\UtsWeb\system\CodeIgniter.php(312): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#6 C:\xampp\htdocs\UtsWeb\public\index.php(45): CodeIgniter\CodeIgniter->run()
#7 C:\xampp\htdocs\UtsWeb\system\Commands\Server\rewrite.php(34): require_once('C:\\xampp\\htdocs...')
#8 {main}
CRITICAL - 2020-12-08 00:58:12 --> Too few arguments to function CodeIgniter\Router\RouteCollection::match(), 2 passed in C:\xampp\htdocs\UtsWeb\app\Config\Routes.php on line 35 and at least 3 expected
#0 C:\xampp\htdocs\UtsWeb\app\Config\Routes.php(35): CodeIgniter\Router\RouteCollection->match(Array, '/kopi')
#1 C:\xampp\htdocs\UtsWeb\system\CodeIgniter.php(780): require('C:\\xampp\\htdocs...')
#2 C:\xampp\htdocs\UtsWeb\system\CodeIgniter.php(364): CodeIgniter\CodeIgniter->tryToRouteIt(Object(CodeIgniter\Router\RouteCollection))
#3 C:\xampp\htdocs\UtsWeb\system\CodeIgniter.php(312): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#4 C:\xampp\htdocs\UtsWeb\public\index.php(45): CodeIgniter\CodeIgniter->run()
#5 C:\xampp\htdocs\UtsWeb\system\Commands\Server\rewrite.php(34): require_once('C:\\xampp\\htdocs...')
#6 {main}
CRITICAL - 2020-12-08 00:59:14 --> Invalid file: /auth.php
#0 C:\xampp\htdocs\UtsWeb\system\View\View.php(228): CodeIgniter\Exceptions\FrameworkException::forInvalidFile('/auth.php')
#1 C:\xampp\htdocs\UtsWeb\system\Common.php(1119): CodeIgniter\View\View->render('/auth', Array, true)
#2 C:\xampp\htdocs\UtsWeb\app\Controllers\Auth.php(10): view('/auth')
#3 C:\xampp\htdocs\UtsWeb\system\CodeIgniter.php(918): App\Controllers\Auth->index()
#4 C:\xampp\htdocs\UtsWeb\system\CodeIgniter.php(404): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Auth))
#5 C:\xampp\htdocs\UtsWeb\system\CodeIgniter.php(312): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#6 C:\xampp\htdocs\UtsWeb\public\index.php(45): CodeIgniter\CodeIgniter->run()
#7 C:\xampp\htdocs\UtsWeb\system\Commands\Server\rewrite.php(34): require_once('C:\\xampp\\htdocs...')
#8 {main}
CRITICAL - 2020-12-08 00:59:19 --> Invalid file: /auth.php
#0 C:\xampp\htdocs\UtsWeb\system\View\View.php(228): CodeIgniter\Exceptions\FrameworkException::forInvalidFile('/auth.php')
#1 C:\xampp\htdocs\UtsWeb\system\Common.php(1119): CodeIgniter\View\View->render('/auth', Array, true)
#2 C:\xampp\htdocs\UtsWeb\app\Controllers\Auth.php(10): view('/auth')
#3 C:\xampp\htdocs\UtsWeb\system\CodeIgniter.php(918): App\Controllers\Auth->index()
#4 C:\xampp\htdocs\UtsWeb\system\CodeIgniter.php(404): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Auth))
#5 C:\xampp\htdocs\UtsWeb\system\CodeIgniter.php(312): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#6 C:\xampp\htdocs\UtsWeb\public\index.php(45): CodeIgniter\CodeIgniter->run()
#7 C:\xampp\htdocs\UtsWeb\system\Commands\Server\rewrite.php(34): require_once('C:\\xampp\\htdocs...')
#8 {main}
CRITICAL - 2020-12-08 00:59:21 --> Invalid file: /auth.php
#0 C:\xampp\htdocs\UtsWeb\system\View\View.php(228): CodeIgniter\Exceptions\FrameworkException::forInvalidFile('/auth.php')
#1 C:\xampp\htdocs\UtsWeb\system\Common.php(1119): CodeIgniter\View\View->render('/auth', Array, true)
#2 C:\xampp\htdocs\UtsWeb\app\Controllers\Auth.php(10): view('/auth')
#3 C:\xampp\htdocs\UtsWeb\system\CodeIgniter.php(918): App\Controllers\Auth->index()
#4 C:\xampp\htdocs\UtsWeb\system\CodeIgniter.php(404): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Auth))
#5 C:\xampp\htdocs\UtsWeb\system\CodeIgniter.php(312): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#6 C:\xampp\htdocs\UtsWeb\public\index.php(45): CodeIgniter\CodeIgniter->run()
#7 C:\xampp\htdocs\UtsWeb\system\Commands\Server\rewrite.php(34): require_once('C:\\xampp\\htdocs...')
#8 {main}
CRITICAL - 2020-12-08 00:59:22 --> Invalid file: /auth.php
#0 C:\xampp\htdocs\UtsWeb\system\View\View.php(228): CodeIgniter\Exceptions\FrameworkException::forInvalidFile('/auth.php')
#1 C:\xampp\htdocs\UtsWeb\system\Common.php(1119): CodeIgniter\View\View->render('/auth', Array, true)
#2 C:\xampp\htdocs\UtsWeb\app\Controllers\Auth.php(10): view('/auth')
#3 C:\xampp\htdocs\UtsWeb\system\CodeIgniter.php(918): App\Controllers\Auth->index()
#4 C:\xampp\htdocs\UtsWeb\system\CodeIgniter.php(404): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Auth))
#5 C:\xampp\htdocs\UtsWeb\system\CodeIgniter.php(312): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#6 C:\xampp\htdocs\UtsWeb\public\index.php(45): CodeIgniter\CodeIgniter->run()
#7 C:\xampp\htdocs\UtsWeb\system\Commands\Server\rewrite.php(34): require_once('C:\\xampp\\htdocs...')
#8 {main}
CRITICAL - 2020-12-08 00:59:22 --> Invalid file: /auth.php
#0 C:\xampp\htdocs\UtsWeb\system\View\View.php(228): CodeIgniter\Exceptions\FrameworkException::forInvalidFile('/auth.php')
#1 C:\xampp\htdocs\UtsWeb\system\Common.php(1119): CodeIgniter\View\View->render('/auth', Array, true)
#2 C:\xampp\htdocs\UtsWeb\app\Controllers\Auth.php(10): view('/auth')
#3 C:\xampp\htdocs\UtsWeb\system\CodeIgniter.php(918): App\Controllers\Auth->index()
#4 C:\xampp\htdocs\UtsWeb\system\CodeIgniter.php(404): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Auth))
#5 C:\xampp\htdocs\UtsWeb\system\CodeIgniter.php(312): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#6 C:\xampp\htdocs\UtsWeb\public\index.php(45): CodeIgniter\CodeIgniter->run()
#7 C:\xampp\htdocs\UtsWeb\system\Commands\Server\rewrite.php(34): require_once('C:\\xampp\\htdocs...')
#8 {main}
CRITICAL - 2020-12-08 00:59:39 --> Invalid file: auth.php
#0 C:\xampp\htdocs\UtsWeb\system\View\View.php(228): CodeIgniter\Exceptions\FrameworkException::forInvalidFile('auth.php')
#1 C:\xampp\htdocs\UtsWeb\system\Common.php(1119): CodeIgniter\View\View->render('auth', Array, true)
#2 C:\xampp\htdocs\UtsWeb\app\Controllers\Auth.php(10): view('auth')
#3 C:\xampp\htdocs\UtsWeb\system\CodeIgniter.php(918): App\Controllers\Auth->index()
#4 C:\xampp\htdocs\UtsWeb\system\CodeIgniter.php(404): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Auth))
#5 C:\xampp\htdocs\UtsWeb\system\CodeIgniter.php(312): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#6 C:\xampp\htdocs\UtsWeb\public\index.php(45): CodeIgniter\CodeIgniter->run()
#7 C:\xampp\htdocs\UtsWeb\system\Commands\Server\rewrite.php(34): require_once('C:\\xampp\\htdocs...')
#8 {main}
CRITICAL - 2020-12-08 00:59:40 --> Invalid file: auth.php
#0 C:\xampp\htdocs\UtsWeb\system\View\View.php(228): CodeIgniter\Exceptions\FrameworkException::forInvalidFile('auth.php')
#1 C:\xampp\htdocs\UtsWeb\system\Common.php(1119): CodeIgniter\View\View->render('auth', Array, true)
#2 C:\xampp\htdocs\UtsWeb\app\Controllers\Auth.php(10): view('auth')
#3 C:\xampp\htdocs\UtsWeb\system\CodeIgniter.php(918): App\Controllers\Auth->index()
#4 C:\xampp\htdocs\UtsWeb\system\CodeIgniter.php(404): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Auth))
#5 C:\xampp\htdocs\UtsWeb\system\CodeIgniter.php(312): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#6 C:\xampp\htdocs\UtsWeb\public\index.php(45): CodeIgniter\CodeIgniter->run()
#7 C:\xampp\htdocs\UtsWeb\system\Commands\Server\rewrite.php(34): require_once('C:\\xampp\\htdocs...')
#8 {main}
CRITICAL - 2020-12-08 01:30:18 --> syntax error, unexpected ';', expecting ']'
#0 C:\xampp\htdocs\UtsWeb\system\Autoloader\Autoloader.php(296): CodeIgniter\Autoloader\Autoloader->requireFile('C:\\xampp\\htdocs...')
#1 C:\xampp\htdocs\UtsWeb\system\Autoloader\Autoloader.php(258): CodeIgniter\Autoloader\Autoloader->loadInNamespace('App\\Controllers...')
#2 [internal function]: CodeIgniter\Autoloader\Autoloader->loadClass('App\\Controllers...')
#3 [internal function]: spl_autoload_call('App\\Controllers...')
#4 C:\xampp\htdocs\UtsWeb\system\CodeIgniter.php(869): class_exists('\\App\\Controller...', true)
#5 C:\xampp\htdocs\UtsWeb\system\CodeIgniter.php(394): CodeIgniter\CodeIgniter->startController()
#6 C:\xampp\htdocs\UtsWeb\system\CodeIgniter.php(312): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#7 C:\xampp\htdocs\UtsWeb\public\index.php(45): CodeIgniter\CodeIgniter->run()
#8 C:\xampp\htdocs\UtsWeb\system\Commands\Server\rewrite.php(34): require_once('C:\\xampp\\htdocs...')
#9 {main}
CRITICAL - 2020-12-08 02:34:12 --> Unknown column 'jumlah' in 'field list'
#0 C:\xampp\htdocs\UtsWeb\system\Database\MySQLi\Connection.php(331): mysqli->query('INSERT INTO `ko...')
#1 C:\xampp\htdocs\UtsWeb\system\Database\BaseConnection.php(741): CodeIgniter\Database\MySQLi\Connection->execute('INSERT INTO `ko...')
#2 C:\xampp\htdocs\UtsWeb\system\Database\BaseConnection.php(669): CodeIgniter\Database\BaseConnection->simpleQuery('INSERT INTO `ko...')
#3 C:\xampp\htdocs\UtsWeb\system\Database\BaseBuilder.php(2249): CodeIgniter\Database\BaseConnection->query('INSERT INTO `ko...', Array, false)
#4 C:\xampp\htdocs\UtsWeb\system\Model.php(755): CodeIgniter\Database\BaseBuilder->insert()
#5 C:\xampp\htdocs\UtsWeb\system\Model.php(574): CodeIgniter\Model->insert(Array, false)
#6 C:\xampp\htdocs\UtsWeb\app\Controllers\Kopi.php(45): CodeIgniter\Model->save(Array)
#7 C:\xampp\htdocs\UtsWeb\system\CodeIgniter.php(918): App\Controllers\Kopi->save()
#8 C:\xampp\htdocs\UtsWeb\system\CodeIgniter.php(404): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Kopi))
#9 C:\xampp\htdocs\UtsWeb\system\CodeIgniter.php(312): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#10 C:\xampp\htdocs\UtsWeb\public\index.php(45): CodeIgniter\CodeIgniter->run()
#11 C:\xampp\htdocs\UtsWeb\system\Commands\Server\rewrite.php(34): require_once('C:\\xampp\\htdocs...')
#12 {main}
CRITICAL - 2020-12-08 02:34:51 --> Unknown column 'jumlah' in 'field list'
#0 C:\xampp\htdocs\UtsWeb\system\Database\MySQLi\Connection.php(331): mysqli->query('INSERT INTO `ko...')
#1 C:\xampp\htdocs\UtsWeb\system\Database\BaseConnection.php(741): CodeIgniter\Database\MySQLi\Connection->execute('INSERT INTO `ko...')
#2 C:\xampp\htdocs\UtsWeb\system\Database\BaseConnection.php(669): CodeIgniter\Database\BaseConnection->simpleQuery('INSERT INTO `ko...')
#3 C:\xampp\htdocs\UtsWeb\system\Database\BaseBuilder.php(2249): CodeIgniter\Database\BaseConnection->query('INSERT INTO `ko...', Array, false)
#4 C:\xampp\htdocs\UtsWeb\system\Model.php(755): CodeIgniter\Database\BaseBuilder->insert()
#5 C:\xampp\htdocs\UtsWeb\system\Model.php(574): CodeIgniter\Model->insert(Array, false)
#6 C:\xampp\htdocs\UtsWeb\app\Controllers\Kopi.php(45): CodeIgniter\Model->save(Array)
#7 C:\xampp\htdocs\UtsWeb\system\CodeIgniter.php(918): App\Controllers\Kopi->save()
#8 C:\xampp\htdocs\UtsWeb\system\CodeIgniter.php(404): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Kopi))
#9 C:\xampp\htdocs\UtsWeb\system\CodeIgniter.php(312): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#10 C:\xampp\htdocs\UtsWeb\public\index.php(45): CodeIgniter\CodeIgniter->run()
#11 C:\xampp\htdocs\UtsWeb\system\Commands\Server\rewrite.php(34): require_once('C:\\xampp\\htdocs...')
#12 {main}
CRITICAL - 2020-12-08 02:37:42 --> Unknown column 'jumlah' in 'field list'
#0 C:\xampp\htdocs\UtsWeb\system\Database\MySQLi\Connection.php(331): mysqli->query('INSERT INTO `ko...')
#1 C:\xampp\htdocs\UtsWeb\system\Database\BaseConnection.php(741): CodeIgniter\Database\MySQLi\Connection->execute('INSERT INTO `ko...')
#2 C:\xampp\htdocs\UtsWeb\system\Database\BaseConnection.php(669): CodeIgniter\Database\BaseConnection->simpleQuery('INSERT INTO `ko...')
#3 C:\xampp\htdocs\UtsWeb\system\Database\BaseBuilder.php(2249): CodeIgniter\Database\BaseConnection->query('INSERT INTO `ko...', Array, false)
#4 C:\xampp\htdocs\UtsWeb\system\Model.php(755): CodeIgniter\Database\BaseBuilder->insert()
#5 C:\xampp\htdocs\UtsWeb\system\Model.php(574): CodeIgniter\Model->insert(Array, false)
#6 C:\xampp\htdocs\UtsWeb\app\Controllers\Kopi.php(45): CodeIgniter\Model->save(Array)
#7 C:\xampp\htdocs\UtsWeb\system\CodeIgniter.php(918): App\Controllers\Kopi->save()
#8 C:\xampp\htdocs\UtsWeb\system\CodeIgniter.php(404): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Kopi))
#9 C:\xampp\htdocs\UtsWeb\system\CodeIgniter.php(312): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#10 C:\xampp\htdocs\UtsWeb\public\index.php(45): CodeIgniter\CodeIgniter->run()
#11 C:\xampp\htdocs\UtsWeb\system\Commands\Server\rewrite.php(34): require_once('C:\\xampp\\htdocs...')
#12 {main}
CRITICAL - 2020-12-08 02:37:45 --> Unknown column 'jumlah' in 'field list'
#0 C:\xampp\htdocs\UtsWeb\system\Database\MySQLi\Connection.php(331): mysqli->query('INSERT INTO `ko...')
#1 C:\xampp\htdocs\UtsWeb\system\Database\BaseConnection.php(741): CodeIgniter\Database\MySQLi\Connection->execute('INSERT INTO `ko...')
#2 C:\xampp\htdocs\UtsWeb\system\Database\BaseConnection.php(669): CodeIgniter\Database\BaseConnection->simpleQuery('INSERT INTO `ko...')
#3 C:\xampp\htdocs\UtsWeb\system\Database\BaseBuilder.php(2249): CodeIgniter\Database\BaseConnection->query('INSERT INTO `ko...', Array, false)
#4 C:\xampp\htdocs\UtsWeb\system\Model.php(755): CodeIgniter\Database\BaseBuilder->insert()
#5 C:\xampp\htdocs\UtsWeb\system\Model.php(574): CodeIgniter\Model->insert(Array, false)
#6 C:\xampp\htdocs\UtsWeb\app\Controllers\Kopi.php(45): CodeIgniter\Model->save(Array)
#7 C:\xampp\htdocs\UtsWeb\system\CodeIgniter.php(918): App\Controllers\Kopi->save()
#8 C:\xampp\htdocs\UtsWeb\system\CodeIgniter.php(404): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Kopi))
#9 C:\xampp\htdocs\UtsWeb\system\CodeIgniter.php(312): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#10 C:\xampp\htdocs\UtsWeb\public\index.php(45): CodeIgniter\CodeIgniter->run()
#11 C:\xampp\htdocs\UtsWeb\system\Commands\Server\rewrite.php(34): require_once('C:\\xampp\\htdocs...')
#12 {main}
CRITICAL - 2020-12-08 02:38:12 --> Allowed fields must be specified for model: App\Models\KopiModel
#0 C:\xampp\htdocs\UtsWeb\system\Model.php(1265): CodeIgniter\Database\Exceptions\DataException::forInvalidAllowedFields('App\\Models\\Kopi...')
#1 C:\xampp\htdocs\UtsWeb\system\Model.php(735): CodeIgniter\Model->doProtectFields(Array)
#2 C:\xampp\htdocs\UtsWeb\system\Model.php(574): CodeIgniter\Model->insert(Array, false)
#3 C:\xampp\htdocs\UtsWeb\app\Controllers\Kopi.php(45): CodeIgniter\Model->save(Array)
#4 C:\xampp\htdocs\UtsWeb\system\CodeIgniter.php(918): App\Controllers\Kopi->save()
#5 C:\xampp\htdocs\UtsWeb\system\CodeIgniter.php(404): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Kopi))
#6 C:\xampp\htdocs\UtsWeb\system\CodeIgniter.php(312): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#7 C:\xampp\htdocs\UtsWeb\public\index.php(45): CodeIgniter\CodeIgniter->run()
#8 C:\xampp\htdocs\UtsWeb\system\Commands\Server\rewrite.php(34): require_once('C:\\xampp\\htdocs...')
#9 {main}
CRITICAL - 2020-12-08 03:18:42 --> Undefined property: App\Controllers\Keranjang::$kopiModel
#0 C:\xampp\htdocs\UtsWeb\app\Controllers\Keranjang.php(47): CodeIgniter\Debug\Exceptions->errorHandler(8, 'Undefined prope...', 'C:\\xampp\\htdocs...', 47, Array)
#1 C:\xampp\htdocs\UtsWeb\system\CodeIgniter.php(918): App\Controllers\Keranjang->edit('kopi-robusta')
#2 C:\xampp\htdocs\UtsWeb\system\CodeIgniter.php(404): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Keranjang))
#3 C:\xampp\htdocs\UtsWeb\system\CodeIgniter.php(312): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#4 C:\xampp\htdocs\UtsWeb\public\index.php(45): CodeIgniter\CodeIgniter->run()
#5 C:\xampp\htdocs\UtsWeb\system\Commands\Server\rewrite.php(34): require_once('C:\\xampp\\htdocs...')
#6 {main}
CRITICAL - 2020-12-08 03:19:01 --> Undefined property: App\Controllers\Keranjang::$kopiModel
#0 C:\xampp\htdocs\UtsWeb\app\Controllers\Keranjang.php(47): CodeIgniter\Debug\Exceptions->errorHandler(8, 'Undefined prope...', 'C:\\xampp\\htdocs...', 47, Array)
#1 C:\xampp\htdocs\UtsWeb\system\CodeIgniter.php(918): App\Controllers\Keranjang->edit('kopi-robusta')
#2 C:\xampp\htdocs\UtsWeb\system\CodeIgniter.php(404): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Keranjang))
#3 C:\xampp\htdocs\UtsWeb\system\CodeIgniter.php(312): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#4 C:\xampp\htdocs\UtsWeb\public\index.php(45): CodeIgniter\CodeIgniter->run()
#5 C:\xampp\htdocs\UtsWeb\system\Commands\Server\rewrite.php(34): require_once('C:\\xampp\\htdocs...')
#6 {main}
CRITICAL - 2020-12-08 03:19:16 --> Call to undefined method App\Models\KeranjangModel::getKopi
#0 C:\xampp\htdocs\UtsWeb\app\Controllers\Keranjang.php(47): CodeIgniter\Model->__call('getKopi', Array)
#1 C:\xampp\htdocs\UtsWeb\system\CodeIgniter.php(918): App\Controllers\Keranjang->edit('kopi-robusta')
#2 C:\xampp\htdocs\UtsWeb\system\CodeIgniter.php(404): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Keranjang))
#3 C:\xampp\htdocs\UtsWeb\system\CodeIgniter.php(312): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#4 C:\xampp\htdocs\UtsWeb\public\index.php(45): CodeIgniter\CodeIgniter->run()
#5 C:\xampp\htdocs\UtsWeb\system\Commands\Server\rewrite.php(34): require_once('C:\\xampp\\htdocs...')
#6 {main}
